apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-web
  labels:
    app: store-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-web
  template:
    metadata:
      labels:
        app: store-web
    spec:
      containers:
      - name: store-web
        image: husniyecapan/store-web
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: store-web-service
spec:
 type: LoadBalancer
 ports:
 - port: 80
 selector:
   app: store-web

