version: '3'

services:
  web:
    build:
      context: .
      dockerfile: StoreApi/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: storeapp/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web
  db:
    image: postgres:15
    restart: always 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB = app_db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
  

   
