---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: store-client
    spec:
      restartPolicy: Always
      containers:
      - name: store-client
        image: husniyecapan/store-client
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: backendUrl
          value: http://storeweb
  selector:
    matchLabels:
      app: store-client
---
apiVersion: v1
kind: Service
metadata:
  name: store-client
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: store-client
